services:
  web:
    build: ./web
    container_name: doleckijakub.pl_web
    healthcheck:
      test: ["CMD-SHELL", "node -e \"fetch('http://localhost:3000').then(r => process.exit(r.ok ? 0 : 1)).catch(() => process.exit(1))\""]
      interval: 1s
      timeout: 15s
      retries: 20
    restart: unless-stopped
    networks:
      doleckijakub.pl:
        aliases:
          - doleckijakub.pl_web
        
    develop:
      watch:
        - action: rebuild
          path: ./web
          target: /app

  api:
    build: ./api
    container_name: doleckijakub.pl_api
    networks:
      doleckijakub.pl:
        aliases:
          - doleckijakub.pl_api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 1s
      timeout: 15s
      retries: 20
    restart: unless-stopped
    env_file: .env
    develop:
      watch:
        - action: rebuild
          path: ./api
          target: /app

  nginx:
    image: nginx:alpine
    container_name: doleckijakub.pl_nginx
    restart: unless-stopped
    ports:
      - "4080:80"
    depends_on:
      - web
      - api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - doleckijakub.pl

networks:
  doleckijakub.pl:
    external: true
